---
output: html_document
css: style.css
title: DagSwadesh
---


***
## Welcome to DagSwadesh!

DagSwadesh (Swadesh lists with village granularity) is a database of Swadesh-100 wordlists from the languages of Daghestan. The main aim of the project is to substantiate lexicostatistical classification of the Nakh-Daghestanian idioms by controlling the provenance of the wordlist at the village level, including using data from reliable sources (such as Kibrik & Kodzasov 1990, 1991) and collecting new data ourselves. Our recordings fill gaps in the existing datasets as well as may account for eventual differences between villages speaking what is conventionally seen as one and the same language. As of 2020, the database presents data on 21 village varieties, belonging to the Avar-Andic branch of the Nakh-Daghestanian.

***
### How to use DagSwadesh?
You can browse DagSwadesh in search mode (in case you are interested in investigating a list from a particular idiom or in inspecting a cognate set) or in comparative mode (in case you want to compare concepts across different idioms). All the data are also available for downloading in tsv cldf-compatible format.

***
### How to cite this project?

>Filatov, Konstantin & Michael Daniel (eds.). *DagSwadesh: 100 Swadesh lists from Daghestan. An online database of    basic vocabulary divergence across neighbour villages.* Moscow: Linguistic Convergence Laboratory, HSE University.   lingconlab.github.io/dagswadesh/index.html.

>К. В. Филатов, Даниэль, М. А. (ред.). *DagSwadesh: Стословные списки Сводеша для языков Дагестана. Онлайн-база      данных дивергенции базовой лексики близлежащих идиомов.* Москва: Международная лаборатория языковой конвергенции,   НИУ ВШЭ. lingconlab.github.io/dagswadesh/index.html.

***
### Contact:
Please contact Konstantin Filatov (`triolo / at / mail / dot / ru`) in case you have any inquiries about the data. If there is a technical issue, please report it here.
